export const AGENTS = [
  {
    id: 'observer',
    label: 'OBSERVER AGENT',
    count: 0,
    icon: '👁',
    bg: '#eef3ff',
    borderColor: '#3b5bdb',
    numColor: '#3b5bdb',
  },
  {
    id: 'rca',
    label: 'RCA AGENT',
    count: 0,
    icon: '🔍',
    bg: '#fff8ee',
    borderColor: '#e67700',
    numColor: '#e67700',
  },
  {
    id: 'decision',
    label: 'DECISION AGENT',
    count: 0,
    icon: '🧠',
    bg: '#f9f0ff',
    borderColor: '#9c36b5',
    numColor: '#9c36b5',
  },
  {
    id: 'selfhealing',
    label: 'SELF-HEALING AGENT',
    count: 0,
    icon: '🔧',
    bg: '#f0fff4',
    borderColor: '#2f9e44',
    numColor: '#2f9e44',
  },
  {
    id: 'dataquality',
    label: 'DATA QUALITY AGENT',
    count: 0,
    icon: '✅',
    bg: '#f0fff4',
    borderColor: '#2f9e44',
    numColor: '#2f9e44',
  },
  {
    id: 'selfservice',
    label: 'SELF-SERVICE AGENT',
    count: 0,
    icon: '💬',
    bg: '#fff0f6',
    borderColor: '#c2255c',
    numColor: '#c2255c',
  },
  {
    id: 'governance',
    label: 'GOVERNANCE AGENT',
    count: 0,
    icon: '🛡',
    bg: '#fff0f6',
    borderColor: '#c2255c',
    numColor: '#c2255c',
  },
]
